/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("java-application")
}

dependencies {
    implementation(project(":shared"))
    implementation("io.confluent:kafka-streams-avro-serde:7.3.1")
}

application {
    // Define the main class for the application.
    mainClass.set("kstreams.playground.app.App")
}
