/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
//    mavenCentral()
//    maven{
//        url = uri("https://packages.confluent.io/maven/")
//    }
}

dependencies {
    implementation("gradle.plugin.com.github.johnrengelman:shadow:7.1.2")
    implementation("com.github.davidmc24.gradle.plugin:gradle-avro-plugin:1.5.0")
    implementation("com.google.cloud.tools:jib-gradle-plugin:3.3.1")
}